site_name: My Cyber Blog
site_url: https://subhan-nizal.github.io
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: indigo
    accent: lime
    scheme: slate
  features:
    - content.code.copy
plugins:
  - search
  - blogging
nav:
  - Home: index.md
  - Projects: projects/index.md
  - Blog: blog/index.md
  - CV: cv.md
  - 'Download CV (Word)': cv.docx
  - LinkedIn: https://www.linkedin.com/in/subhan-nizal-39aa38345
  - Projects:
      - Security Event Analysis: projects/security_events_2025-07-22.md
      - Security Event Timeline: projects/security_timeline_2025-07-22.md
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/subhan-nizal-39aa38345
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/subhan-nizal
      name: GitHub
    - icon: fontawesome/regular/file-word
      link: cv.docx
      name: Download CV (Word)
extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-G8FJQPDE4D
  - js/ga-tracking.js
  - https://plausible.io/js/plausible.js